# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EliteCake' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CountryPickerSwift'
  pod 'CountryPickerView'
  pod 'Cosmos', '~> 23.0'
  pod 'GoogleSignIn', '~> 5.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'iOSDropDown'
  pod 'dotLottie'
  pod 'lottie-ios', '~> 3.2.0'
  pod 'GoogleMaps'
  pod 'OTPFieldView'
  pod 'FirebaseMessaging', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'GooglePlaces'
  pod 'GoogleMaps', '8.0.0'
  
  
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  end
  
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      flutter_additional_ios_build_settings(target)
#      target.build_configurations.each do |config|
#      xcconfig_path = config.base_configuration_reference.real_path
#      xcconfig = File.read(xcconfig_path)
#      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
#      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
#      end
#    end
#  end
